updated docker compose section
BassT23/Proxmox pull request #128
Opened 2024-04-29 09:50 UTC by pythongod

updated docker compose section to find more docker compose files and use docker compose to update

not tested with docker compose v1

2024-04-29 10:02 UTC, Gauvino commented
First of all, thank for your contribution it help the project a lot, I'm gonna review this when im home and also try to tested it with docker compose v1 to make sure
And also request some typo change !

2024-05-01 20:53 UTC, Gauvino commented on update-extras.sh
> +    done < <(find /home -name "$COMPOSEFILE" -exec dirname {} \; 2> >(grep -v 'Permission denied'))
After only testing it, it doesn't found compose file in /root, maybe because it's searching in /home

2024-05-01 21:14 UTC, Gauvino requested changes

2024-05-01 21:14 UTC, Gauvino commented on update-extras.sh
> +        echo "No Docker Compose files found anywhere."
```suggestion
        echo "Ultimate-Updater asn't found any Docker Compose files."
```

2024-05-02 06:17 UTC, Gauvino commented on update-extras.sh
> +    done < <(find /home -name "$COMPOSEFILE" -exec dirname {} \; 2> >(grep -v 'Permission denied'))
That's what I was thinking, the script could have problem if on a their is a LXC container running portainer trying to update the docker compose contain in portainer

2024-05-02 12:09 UTC, Gauvino commented
Im gonna try the v1 when I have time

2024-05-02 16:32 UTC, BassT23 commented on update-extras.sh
> +fi
Could you pls test this version ;)
compose files must be in `/home`

2024-05-03 13:55 UTC, BassT23 approved these changes

2024-05-03 13:56 UTC, merged

2024-05-03 13:56 UTC, Gauvino commented
Why merging already ??????

2024-05-03 13:57 UTC, BassT23 commented
you made the changes ;) so ist approved from you, or not?

2024-05-03 13:59 UTC, Gauvino commented
> you made the changes ;) so ist approved from you, or not?

No I will approved the change for real if i did click on approved the change, the changed work, I tested it and and request other change.